#!/usr/bin/env ruby
# vi: ft=ruby

require 'erb'
require 'yaml'

class SongList
  def initialize(directory)
    here = File.expand_path(".")
    path = File.join(here, directory, "/*.txt")
    files = Dir.glob(path)
    @songs = files.collect do |f|
      Song.new(f)
    end
  end

  def render
    ERB.new(DATA.read).result(binding)
  end
end

class Song
  attr_reader :file

  def initialize(file)
    @file = File.open(file)
  end

  def title
    front_matter["title"]
  end

  def body
    @body ||= contents.split("---").last
  end

  def contents
    @contents ||= @file.read
  end

  def front_matter
    @front_matter ||= YAML.load(contents)
  end
end

puts SongList.new(ARGV[0]).render

__END__
<html>
<head>
  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css">
</head>
<body>
<div class="container">
  <h1>
    It's sing along time!!!
  </h1>
  <% @songs.each do |song| %>
    <div class="panel song">
      <h2><%= song.title %></h2>
      <pre>
        <%= song.body  %>
      </pre>
  </div>
  <% end %>
</div>
</body>
</html>
